### ISSUE TITLE
Additional Measurements

### ISSUE THREAD

**Issue by michis0806** [fasmide/deflux#3]
Hi @fasmide 
as my iobroker.deconz to InfluxDB breaks with iobroker.deconz@1.2.6 I was looking exactly for something like this.
Your Code works fine for most of my sensors but lacks support for some values:

`2020/03/12 08:12:18 recv: {"e":"changed","id":"6","r":"sensors","state":{"dark":false,"daylight":false,"lastupdated":"2020-03-12T08:12:18","lightlevel":15180,"lux":33},"t":"event","uniqueid":"00:17:88:
01:06:f6:6e:ca-02-0400"}                                                                                                                                                                                 
2020/03/12 08:12:18 Dropping event due to error: unable to parse message: unable to unmarshal state: unable to unmarshal event state: ZHALightLevel is not a known type`

`2020/03/12 08:13:13 recv: {"e":"changed","id":"15","r":"sensors","state":{"lastupdated":"2020-03-12T08:13:13","presence":true},"t":"event","uniqueid":"00:17:88:01:06:47:1f:1e-02-0406"}                 
2020/03/12 08:13:13 Dropping event due to error: unable to parse message: unable to unmarshal state: unable to unmarshal event state: ZHAPresence is not a known type`

`020/03/12 08:15:13 recv: {"e":"changed","id":"20","r":"sensors","state":{"lastupdated":"2020-03-12T08:15:13","presence":true},"t":"event","uniqueid":"vpir-1581106741418"}
2020/03/12 08:15:13 Dropping event due to error: unable to parse message: unable to unmarshal state: unable to unmarshal event state: CLIPPresence is not a known type`

`2020/03/12 08:21:22 recv: {"e":"changed","id":"37","r":"sensors","state":{"lastupdated":"2020-03-12T08:21:22","open":true},"t":"event","uniqueid":"00:15:8d:00:04:46:d4:f6-01-0006"}                     
2020/03/12 08:21:22 Dropping event due to error: unable to parse message: unable to unmarshal state: unable to unmarshal event state: ZHAOpenClose is not a known type `

`2020/03/12 08:23:22 recv: {"e":"changed","id":"37","r":"sensors","state":{"lastupdated":"2020-03-12T08:23:22","vibration":true},"t":"event","uniqueid":"00:15:8d:00:03:13:0d:2c-01-0101"}                     
2020/03/12 08:21:22 Dropping event due to error: unable to parse message: unable to unmarshal state: unable to unmarshal event state: ZHAVibration is not a known type `

Is there any chance to add them? 

Thanks
Michael

**Comment by fasmide** [comment]
Well, it seems you fixed this :) Once again thanks for sharing :)
